[package]
name = "paddle_strike_amethyst"
version = "0.1.0"
authors = ["Milo Hao XU (milo.h.xu@icloud.com)"]
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst" }

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
